#!/bin/sh

echo "Install Vim Plug"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Install .vimrc at $HOME/.vimrc"
cp ./vimrc ~/.vimrc

echo "Install Vim packages"
vim +PlugInstall +qall

echo "Install Complete"

