#!/bin/bash

echo "[VIM]: Install vim at $OSTYPE"
if [[ "$OSTYPE" == "linux-gnu" ]]; then
  # Centos
  if [ -f /etc/redhat-release ]; then
    echo "[VIM]: TODO install vim 8.0 on Centos"
  fi

  # Ubuntu
  if [ -f /etc/lsb-release ]; then
    # docker: check sudo command exists
    if ! command -v sudo &> /dev/null; then
      add-apt-repository -y ppa:jonathonf/vim
      apt update -y
      apt install -y vim curl

      # vim-css-color need to install gvim
      apt install -y vim-common
    else
      sudo add-apt-repository -y ppa:jonathonf/vim
      sudo apt update -y
      sudo apt install -y vim curl

      # vim-css-color need to install gvim
      sudo apt install -y vim-common
    fi
  fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
  # Mac OSX
  brew install vim
  # vim-css-color need to install macvim
  # brew install macvim
elif [[ "$OSTYPE" == "cygwin" ]]; then
  # POSIX compatibility layer and Linux environment emulation for Windows
  echo "[VIM]: TODO install vim on $OSTYPE"
elif [[ "$OSTYPE" == "msys" ]]; then
  # Lightweight shell and GNU utilities compiled for Windows (part of MinGW)
  echo "[VIM]: TODO install vim on $OSTYPE"
elif [[ "$OSTYPE" == "win32" ]]; then
  # I'm not sure this can happen.
  echo "[VIM]: TODO install vim on $OSTYPE"
elif [[ "$OSTYPE" == "freebsd"* ]]; then
  # ...
  echo "[VIM]: TODO install vim on $OSTYPE"
else
  # Unknown.
  echo "[VIM]: TODO install vim on $OSTYPE"
fi

echo "[VIM]: Backup $HOME/.vimrc to $HOME/.vimrc.bak"
if [[ -f "~/.vimrc" ]];
then
  mv ~/.vimrc ~/.vimrc.bak
fi

echo "[VIM]: Install at $HOME/.vimrc"
cp ./vimrc ~/.vimrc

echo "[VIM]: Install Vim Plug"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "[VIM]: Install Vim packages"
vim +PlugInstall +qall

echo "[VIM]: Install Complete"

