#!/bin/bash

echo "[VIM]: Install vim at $OSTYPE"
if [[ "$OSTYPE" == "linux-gnu" ]]; then
  if [ -f /etc/redhat-release ]; then
    echo "[VIM]: TODO install vim 8.0 on Centos"
  fi

  if [ -f /etc/lsb-release ]; then
    sudo add-apt-repository -y ppa:jonathonf/vim
    sudo apt update -y
    sudo apt install -y vim
  fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
  # Mac OSX
  brew install vim
elif [[ "$OSTYPE" == "cygwin" ]]; then
  # POSIX compatibility layer and Linux environment emulation for Windows
  echo "[VIM]: TODO install vim on $OSTYPE"
elif [[ "$OSTYPE" == "msys" ]]; then
  # Lightweight shell and GNU utilities compiled for Windows (part of MinGW)
  echo "[VIM]: TODO install vim on $OSTYPE"
elif [[ "$OSTYPE" == "win32" ]]; then
  # I'm not sure this can happen.
  echo "[VIM]: TODO install vim on $OSTYPE"
elif [[ "$OSTYPE" == "freebsd"* ]]; then
  # ...
  echo "[VIM]: TODO install vim on $OSTYPE"
else
  # Unknown.
  echo "[VIM]: TODO install vim on $OSTYPE"
fi

echo "[VIM]: Backup $HOME/.vimrc to $HOME/.vimrc.bak"
if [[ -f "~/.vimrc" ]];
then
  mv ~/.vimrc ~/.vimrc.bak
fi

echo "[VIM]: Install at $HOME/.vimrc"
cp ./vimrc ~/.vimrc

echo "[VIM]: Install Vim Plug"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "[VIM]: Install Vim packages"
vim +PlugInstall +qall

echo "[VIM]: Install Complete"

