set nocompatible              " be iMproved, required
filetype off                  " required

set directory=/tmp             " set swap file path

call plug#begin()

Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'mg979/vim-visual-multi'
Plug 'airblade/vim-gitgutter'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

" Optional
Plug 'junegunn/vim-easy-align'
" Plug 'mbbill/undotree'
" Plug 'rstacruz/sparkup', {'rtp': 'vim'}

" Syntax highlighting
Plug 'itchyny/lightline.vim' " Light line status bar
Plug 'ap/vim-css-color'
" Plug 'nikvdp/ejs-syntax', { 'for': 'ejs' }
" Plug 'posva/vim-vue', { 'for': 'vue' }
" Plug 'rhysd/vim-crystal', { 'for': ['cr', 'crystal'] }
" Plug 'slim-template/vim-slim', { 'for': ['slim'] }
" Plug 'prettier/vim-prettier', { 'do': 'npm install', 'for': ['javascript', 'typescript', 'css', 'less', 'scss'] }
" Plug 'vale1410/vim-minizinc', { 'for': ['mzn', 'fzn'] }

call plug#end()

" Install
" vim +PlugInstall
" vim +PlugInstall +qall
" :PlugInstall
" vim-go
" :GoInstallBinaries

filetype plugin indent on    " required

" Put your non-Plugin stuff after this line

" ---- Settings ----
set number
set autoindent
set smartindent
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab
set nowrap
