#!/bin/bash

source ../utils

echo "[DOCKER]: Install docker at $OSTYPE"
if [[ "$OSTYPE" == "linux-gnu" ]]; then
  # Centos
  if [ -f /etc/redhat-release ]; then
    echo "[DOCKER]: TODO install docker 8.0 on Centos"
  fi

  # Ubuntu
  if [ -f /etc/lsb-release ]; then
    $sh_c "apt update -yqq"
    $sh_c "apt install -yqq curl"
    $sh_c "curl -fsSL https://get.docker.com | sh"
  fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
  # Mac OSX
  echo "[DOCKER]: TODO install docker on $OSTYPE"
elif [[ "$OSTYPE" == "cygwin" ]]; then
  # POSIX compatibility layer and Linux environment emulation for Windows
  echo "[DOCKER]: TODO install docker on $OSTYPE"
elif [[ "$OSTYPE" == "msys" ]]; then
  # Lightweight shell and GNU utilities compiled for Windows (part of MinGW)
  echo "[DOCKER]: TODO install docker on $OSTYPE"
elif [[ "$OSTYPE" == "win32" ]]; then
  # I'm not sure this can happen.
  echo "[DOCKER]: TODO install docker on $OSTYPE"
elif [[ "$OSTYPE" == "freebsd"* ]]; then
  # ...
  echo "[DOCKER]: TODO install docker on $OSTYPE"
else
  # Unknown.
  echo "[DOCKER]: TODO install docker on $OSTYPE"
fi

echo "[DOCKER]: Install Complete"

