#!/bin/bash

source ../utils

echo "[TMUX]: Install tmux at $OSTYPE"
if [[ "$OSTYPE" == "linux-gnu" ]]; then
  if [ -f /etc/lsb-release ]; then
    # Ubuntu
    echo "[TMUX]: Install tmux on ubuntu"
    $sh_c "apt update -yqq"
    $sh_c "apt install -yqq tmux"
  elif [ -f /etc/redhat-release ]; then
    # Centos
    echo "[TMUX]: TODO install tmux on Centos"
  else
    # Unknown.
    echo "[TMUX]: TODO install tmux on $OSTYPE"
  fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
  # Mac OSX
  brew install tmux
else
  # Unknown.
  echo "[TMUX]: TODO install tmux on $OSTYPE"
fi

echo "[TMUX]: Backup $HOME/.tmux.conf to $HOME/.tmux.conf.bak"
if [[ -f "~/.tmux.conf" ]];
then
  mv ~/.tmux.conf ~/.tmux.conf.bak
fi

echo "[TMUX]: Install at $HOME/.tmux.conf"
cp ./tmux.conf ~/.tmux.conf

echo "[TMUX]: Install Complete"

