#!/bin/bash

echo "[VIM]: Install vim at $OSTYPE"
if [[ "$OSTYPE" == "linux-gnu" ]]; then
  if [ -f /etc/lsb-release ]; then
    # Ubuntu
    echo "[TMUX]: Istall tmux on ubuntu"
    sudo apt update -y
    sudo apt install -y tmux
  elif [ -f /etc/redhat-release ]; then
    # Centos
    echo "[VIM]: TODO install tmux on Centos"
  else
    # Unknown.
    echo "[VIM]: TODO install vim on $OSTYPE"
  fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
  # Mac OSX
  brew install tmux
else
  # Unknown.
  echo "[VIM]: TODO install vim on $OSTYPE"
fi

echo "[TMUX]: Backup $HOME/.tmux.conf to $HOME/.tmux.conf.bak"
if [[ -f "~/.tmux.conf" ]];
then
  mv ~/.tmux.conf ~/.tmux.conf.bak
fi

echo "[TMUX]: Install at $HOME/.tmux.conf"
cp ./tmux.conf ~/.tmux.conf

echo "[TMUX]: Install Complete"

